apiVersion: v1
kind: Service
metadata:
    name: node-webapp
spec:
    ports:
      - port:  80
        targetPort: 3000
        protocol: TCP
    selector:
        name: node-webpp
    type: LoadBalancer
    